name: semantic_ui_angular_dart
description: Semantic UI for Angular Dart
version: 0.1.6
author: Nick Ng <ngyewch@gmail.com>
homepage: https://github.com/ngyewch/semantic-ui-angular-dart

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular2: '>=2.0.0 <3.0.0'
  browser: ^0.10.0
  http: ^0.11.0

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
